/*
 Navicat Premium Data Transfer

 Source Server         : localhost_3306
 Source Server Type    : MySQL
 Source Server Version : 80029
 Source Host           : localhost:3306
 Source Schema         : question

 Target Server Type    : MySQL
 Target Server Version : 80029
 File Encoding         : 65001

 Date: 08/07/2022 20:05:32
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for list
-- ----------------------------
DROP TABLE IF EXISTS `list`;
CREATE TABLE `list`  (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `question` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `answer` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 611 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of list
-- ----------------------------
INSERT INTO `list` VALUES (1, '这是', 'test');
INSERT INTO `list` VALUES (2, '测试', '123');
INSERT INTO `list` VALUES (3, '提神饮料中主要因为含有哪种物质，才会使人提神醒脑，恢复精力？', '咖啡因');
INSERT INTO `list` VALUES (4, '中国古代记载的“司南”是哪种伟大发明的早起雏形？', '指南针');
INSERT INTO `list` VALUES (5, '形容人极其圆滑的俗语“见人说人话”的下一句是什么？', '见鬼说鬼话');
INSERT INTO `list` VALUES (6, '骆驼的驼峰中主要贮藏的是哪种油性物质？', '脂肪');
INSERT INTO `list` VALUES (7, '登雪山时不能大声说话，因为声音的振动会引发哪种自然灾害？', '雪崩');
INSERT INTO `list` VALUES (8, '斯芬克斯是哪个埃及标志性建筑物的名字？', '狮身人面像');
INSERT INTO `list` VALUES (9, '这张课本插图中出现了哪座桥？', '泸定桥');
INSERT INTO `list` VALUES (10, '“月上柳梢头，人约黄昏后”描写的是哪个传统节日？', '元宵节');
INSERT INTO `list` VALUES (11, '毕达哥拉斯定理”在中国又被称为什么定理？', '勾股定理');
INSERT INTO `list` VALUES (12, '动漫《名侦探柯南》中，毛利兰是哪项武术运动的高手？', '空手道');
INSERT INTO `list` VALUES (13, '近日美洲峰会上奥巴马与卡斯特罗的握手标志着美国与哪个国家的关系进一步解冻？', '古巴');
INSERT INTO `list` VALUES (14, '世界上第二大的流动沙漠是位于中国的什么沙漠？', '塔克拉玛干沙漠');
INSERT INTO `list` VALUES (15, '我国第一条铁路“京张铁路线”是在哪位近代铁路专家的主持下建造的？', '詹天佑');
INSERT INTO `list` VALUES (16, '南美洲最常用到的语言是西班牙语和什么语言？', '葡萄牙语');
INSERT INTO `list` VALUES (17, '课文《十里长街送总理》中的“十里长街”指的是北京的那条街道？', '长安街');
INSERT INTO `list` VALUES (18, '哪种花因为母亲节的兴起而成为全球销量最大的花卉？', '康乃馨');
INSERT INTO `list` VALUES (19, '“欧姆”在物理学中是哪种物理量的单位？', '电阻');
INSERT INTO `list` VALUES (20, '2015年4月9日，美国航空局宣布41981号小行星将以哪位内地已故女歌手命名？', '姚贝娜');
INSERT INTO `list` VALUES (21, '“中”字的笔画的第4笔试什么？', '竖');
INSERT INTO `list` VALUES (22, '占空气成为78%的是哪种气体？', '氮气');
INSERT INTO `list` VALUES (23, '太阳系曾经的九大行星中，哪一颗在2006年被踢出了“行星”行列？', '冥王星');
INSERT INTO `list` VALUES (24, '（脑洞题）一头公鹿在地上跑的飞快，跑着跑着就变成了什么？', '高速公路');
INSERT INTO `list` VALUES (25, '世界三大短篇小说巨匠指的是俄国的契诃夫、美国的欧亨利和哪位法国作家？', '莫泊桑');
INSERT INTO `list` VALUES (26, '《小星星变奏曲》是哪位奥地利作曲家所作的钢琴曲？', '莫扎特');
INSERT INTO `list` VALUES (27, '如果你想一睹美人鱼雕像的风采，那么你要前往欧洲的哪个国家？', '丹麦');
INSERT INTO `list` VALUES (28, '在《三国演义》中，刘备最开始是以卖什么为生的？', '草鞋');
INSERT INTO `list` VALUES (29, '韩国组合EXO的前任队长是哪位中国人？', '吴亦凡');
INSERT INTO `list` VALUES (30, '美洲地区的土著原住民大部分是什么种族的人？', '印第安人');
INSERT INTO `list` VALUES (31, '2015年4月，美国哪位政坛女强人宣布将第二次参与美国总统大选？', '希拉里');
INSERT INTO `list` VALUES (32, '（脑洞题）什么样的山和海可以移动？', '人山人海');
INSERT INTO `list` VALUES (33, '“说、学、逗、唱”是我国哪种传统艺术的基本功？', '相声');
INSERT INTO `list` VALUES (34, '成语“五大三粗”中的三粗指的是腰粗、腿粗和什么粗？', '脖子粗');
INSERT INTO `list` VALUES (35, '恐龙大约灭绝于中生代的那个时期？', '白垩纪');
INSERT INTO `list` VALUES (36, 'WindowsXP、Win7都是计算机什么系统的代表型号？', '操作系统');
INSERT INTO `list` VALUES (37, '“这是个人的一小步，却是人类的一大步”是哪位美国宇航员登上月球后说出的名言？', '阿姆斯特朗');
INSERT INTO `list` VALUES (38, '被称为“世界美术史上最美的一只手”出现在哪幅名画上面？', '蒙娜丽莎');
INSERT INTO `list` VALUES (39, '英国历史上哪个首相被民众亲切地称呼为“老虎狗”？', '丘吉尔');
INSERT INTO `list` VALUES (40, '美国的哪条河流被马克吐温比喻为“削下来的长又弯曲的苹果皮”？', '密西西比河');
INSERT INTO `list` VALUES (41, '1907 年日本科学家偶然地从海带中提取出了哪种调味品？', '味精');
INSERT INTO `list` VALUES (42, '2015 年 5 月宣布退出综艺圈的是哪位音乐人？', '高晓松');
INSERT INTO `list` VALUES (43, '世界上第一条地铁出现于欧洲的哪座城市？', '伦敦');
INSERT INTO `list` VALUES (44, '图中所示的是哪位女明星近日在香港拍摄的杂志写真？', '周迅');
INSERT INTO `list` VALUES (45, '美式橄榄球运动中，进攻方的灵魂人物是哪个位置的球员？', '四分卫');
INSERT INTO `list` VALUES (46, '青尼罗河和白尼罗河在哪个非洲国家交汇？', '苏丹');
INSERT INTO `list` VALUES (47, '发掘和培养了金秀贤的韩国明星是谁？', '裴勇俊');
INSERT INTO `list` VALUES (48, '现代钢琴从外形上主要分成立式钢琴和哪种钢琴？', '三角钢琴');
INSERT INTO `list` VALUES (49, '生物分类学上，鲸鱼与哪种海洋生物是近亲？', '海豚');
INSERT INTO `list` VALUES (50, '旧金山指的是美国的圣弗朗西斯科，那么新金山指的是哪座澳洲城市？', '墨尔本');
INSERT INTO `list` VALUES (51, '2015 年情人节，哪位意大利巧克力大亨与世长辞？', '费列罗');
INSERT INTO `list` VALUES (52, '奥运火炬的起源和哪位古希腊的神话人物有关？', '普罗米修斯');
INSERT INTO `list` VALUES (53, '“COCO 小姐”指的是哪位法国历史上的时装设计师？', '香奈儿');
INSERT INTO `list` VALUES (54, '图中所示的是哪位已退役的运动员？', '泰森');
INSERT INTO `list` VALUES (55, '诗句“家祭无忘告乃翁”中的“翁”指的是哪位诗人？', '陆游');
INSERT INTO `list` VALUES (56, '传说哪位明代诗人为了秋香，甘愿化名华安入宰相府为奴？', '唐伯虎');
INSERT INTO `list` VALUES (57, '林俊杰的哪首歌地歌名包含了两种早餐食物？', '豆浆油条');
INSERT INTO `list` VALUES (58, '原产于墨西哥，因为色彩娇艳，最初仅被当作观赏植物的是哪种蔬果？', '番茄');
INSERT INTO `list` VALUES (59, '英国伦敦泰晤士河畔的“伦敦眼”是哪种游乐设施？', '摩天轮');
INSERT INTO `list` VALUES (60, '别中国网友称为“小七公主”的是哪位足球明星的女儿？', '贝克汉姆');
INSERT INTO `list` VALUES (61, '新中国成立以来最严重的一次特大森林火灾发生在黑龙江省的哪个山区？', '大兴安岭');
INSERT INTO `list` VALUES (62, '2015 年 5 月以自己粉丝的名义捐赠尼泊尔灾区 1 亿韩元的是哪位韩国男明星? ', '李敏镐');
INSERT INTO `list` VALUES (63, '《红色的葡萄园》是哪位画家生前卖出的唯一作品？', '梵高');
INSERT INTO `list` VALUES (64, '美国俄亥俄州的首府与哪位大航海家同名？', '哥伦布');
INSERT INTO `list` VALUES (65, '“钟情妄想症”在中医上就是哪种病症？', '花痴');
INSERT INTO `list` VALUES (66, '位于紫禁城坤宁宫后方的园林，明代称为宫后苑，而在清代被称为什么？', '御花园');
INSERT INTO `list` VALUES (67, '美国国家橄榄球联盟的年度冠军赛被称为什么杯？', '超级碗');
INSERT INTO `list` VALUES (68, '“海男子”是哪种海鲜地别名？', '海参');
INSERT INTO `list` VALUES (69, '“要钱太守”说的是三国时期的哪位大将？', '曹仁');
INSERT INTO `list` VALUES (70, '姜文电影《太阳照常升起》与哪位美国作家的长篇小说同名？', '海明威');
INSERT INTO `list` VALUES (71, '苏轼的诗句“粗缯大布裹生涯”的下一句是什么？', '腹有诗书气自华');
INSERT INTO `list` VALUES (72, '国际爱护动物基金会承认的两座大象孤儿院，位于肯尼亚和哪个非洲国家？', '斯里兰卡');
INSERT INTO `list` VALUES (73, '每方三名球员参加的街头篮球比赛俗称是什么？', '斗牛');
INSERT INTO `list` VALUES (74, '“轻轻移，慢慢提，先开窗，后喝汤”说的是我国哪种小吃的吃法？', '小笼包');
INSERT INTO `list` VALUES (75, '“其式五，其数七，其变化之式多至千余”是对我国哪种传统益智玩具的描述？', '七巧板');
INSERT INTO `list` VALUES (76, '职业相扑选手是通过吃哪种料理来快速增肥的？', '火锅');
INSERT INTO `list` VALUES (77, '“温酒斩华雄”的典故中，为关羽斟下温酒的是哪位三国人物？', '曹操');
INSERT INTO `list` VALUES (78, '“精卫填海”中的“精卫”是哪位传说人物的女儿？', '炎帝');
INSERT INTO `list` VALUES (79, '现在发行的 5 美元纸币上印有哪位总统的头像？', '林肯');
INSERT INTO `list` VALUES (80, '长江发源于我国青藏高原的哪座山上？', '唐古拉山');
INSERT INTO `list` VALUES (81, '勇敢狡黠的佐罗，其名字是西班牙语中的哪种动物？', '狐狸');
INSERT INTO `list` VALUES (82, '著名好望角位于南非的哪座港口城市？', '开普敦');
INSERT INTO `list` VALUES (83, '由 186 封书信编辑而成的是哪部极具教育意义的名著？', '傅雷家书');
INSERT INTO `list` VALUES (84, '橙子是橘子和哪种水果杂交的品种？', '柚子');
INSERT INTO `list` VALUES (85, '2015 年 4 月在网上引起热议的 10 字辞职信，内容是“世界那么大”和什么？', '我想去看看');
INSERT INTO `list` VALUES (86, '国际禁毒日的确立与我国哪位民族英雄有关？', '林则徐');
INSERT INTO `list` VALUES (87, '中国剪刀行业的老字号，“南有张小泉”北有哪个品牌？', '王麻子');
INSERT INTO `list` VALUES (88, '“既然选择了远方，便只顾风雨兼程”是哪位诗人的诗句？', '汪国真');
INSERT INTO `list` VALUES (89, '在电视剧《虎妈猫爸》中饰演“猫爸”罗素的是哪位男演员？', '佟大为');
INSERT INTO `list` VALUES (90, '鲁智深削发为僧之前在经略府任什么官职？', '提辖');
INSERT INTO `list` VALUES (91, '已上映的“宫”系列电视剧有《宫锁心玉》《宫锁连珠》和什么？', '宫锁连城');
INSERT INTO `list` VALUES (92, '以面包干发酵酿制而成，颜色近似啤酒的是哪种俄国饮料？', '格瓦斯');
INSERT INTO `list` VALUES (93, '赢得 2015 年世博会举办权的是意大利的哪座城市？', '米兰');
INSERT INTO `list` VALUES (94, '如果一枚古代铜钱上刻有“开元通宝”四字，那么这是哪个朝代铸造的钱币？', '唐朝');
INSERT INTO `list` VALUES (95, '中国和朝鲜之间的界河是那条江？', '鸭绿江');
INSERT INTO `list` VALUES (96, '那种鸟喜欢把蛋下在其他鸟类的巢里？', '杜鹃');
INSERT INTO `list` VALUES (97, '北京大学的前身“京师大学堂”是在哪场清末运动中创办的？', '洋务运动');
INSERT INTO `list` VALUES (98, '杜牧诗句中名句“路上行人欲断魂”描写的是中国哪个传统节日？', '清明节');
INSERT INTO `list` VALUES (99, '日则沟、诺日朗瀑布等景点位于我国哪个风景区？', '九寨沟');
INSERT INTO `list` VALUES (100, '太阳大气从内到外分别是光球层、色球层和什么层？', '日冕层');
INSERT INTO `list` VALUES (101, '毛里求斯的国鸟是哪种已经灭绝的鸟类？', '渡渡鸟');
INSERT INTO `list` VALUES (102, '哈利法塔就是我们俗称的哪座建筑？', '迪拜塔');
INSERT INTO `list` VALUES (103, '人体中最小的骨骼是位于耳朵的什么骨？', '听小骨');
INSERT INTO `list` VALUES (104, '电影《茜茜公主》中，茜茜公主嫁给了哪个国家的国王？', '奥地利');
INSERT INTO `list` VALUES (105, '研制出第一艘飞艇的是哪位德国工程师？', '齐柏林');
INSERT INTO `list` VALUES (106, '获得 2015 年 NBA 常规赛 MVP 的是哪位运动员？', '顾里');
INSERT INTO `list` VALUES (107, '传说被一只从天上掉下来的乌龟砸死的是哪位古希腊悲剧作家？', '埃斯库罗斯');
INSERT INTO `list` VALUES (108, '确定了水是化合物而非单质的是哪位英国物理学家？', '卡文迪许');
INSERT INTO `list` VALUES (109, '2015 年由古天乐、吴镇宇、张智霖主演，以航空为题材的是哪部电影？', '冲上云霄');
INSERT INTO `list` VALUES (110, '《论语》在体裁上属于什么体的经典？', '语录体');
INSERT INTO `list` VALUES (111, '因含有丰富的蛋白质和脂类，而被称为“热带水果之王”的是哪种气味独特的水果？', '榴莲');
INSERT INTO `list` VALUES (112, '青蛙出了用肺呼吸外，还能用身体的什么部位呼吸？', '皮肤');
INSERT INTO `list` VALUES (113, '哪位中国运动员在2015年劳伦斯奖颁奖典礼上获得“特别成就奖”？', '李娜');
INSERT INTO `list` VALUES (114, '小说《夏洛的网》的主角夏洛是一只什么动物？', '蜘蛛');
INSERT INTO `list` VALUES (115, '古代欧洲，水手们出海时会携带大量橙子是为了防止什么病的发生：', '坏血症');
INSERT INTO `list` VALUES (116, ' 被蒲松龄描述为“一物竟能兼东植”的是哪种中药材？', '冬虫夏草');
INSERT INTO `list` VALUES (117, '这张语文课本插图中的任务是谁？', '爱迪生');
INSERT INTO `list` VALUES (118, '《繁星春水》的作者是我国哪位著名作家？', '冰心');
INSERT INTO `list` VALUES (119, '近日哪部系列电影以首日近4亿的票房刷新了中国院线的历史记录？', '速度与激情7');
INSERT INTO `list` VALUES (120, '“龟派气功”是日本哪部动漫中出现次数最多的武功？', '七龙珠');
INSERT INTO `list` VALUES (121, '国际上通用的黄金重量单位叫什么？', '盎司');
INSERT INTO `list` VALUES (122, '在化学方程式中，“Δ”代表什么操作？', '加热');
INSERT INTO `list` VALUES (123, '“爷娘闻女来，出郭相扶将”中的“女”指的是哪位历史人物？', '花木兰');
INSERT INTO `list` VALUES (124, '因单条微博评论过百万而创下吉尼斯世界纪录，被评为2015年微博KING的是哪位人气男明星？', '鹿晗');
INSERT INTO `list` VALUES (125, '这幅油画描绘了近代历史上那次起义的前夜？', '南昌起义');
INSERT INTO `list` VALUES (126, ' 第二亚欧大陆桥的终点位于哪个欧洲城市？', '鹿特丹');
INSERT INTO `list` VALUES (127, '“秦淮八艳”原本只有六艳，后人将“柳如是”和哪个女子加入其中才凑成了“八艳”？', '陈圆圆');
INSERT INTO `list` VALUES (128, '“我亦无他，惟手熟尔”出自欧阳修写的那篇文章？', '卖油翁');
INSERT INTO `list` VALUES (129, '著名的港式甜品“杨枝甘露”，它的主要食材分别是柚子以及哪种水果？', '芒果');
INSERT INTO `list` VALUES (130, '在中小学的语文考试中，哪种题型占的分值最大？', '作文');
INSERT INTO `list` VALUES (131, '“0纬线”指的是哪条地球上的特殊纬线？', '赤道');
INSERT INTO `list` VALUES (132, '成语“如花似玉”运用的是哪种修辞手法？', '比喻');
INSERT INTO `list` VALUES (133, '凡尔纳的三部曲分别是《格兰特船长的儿女》，《神秘岛》和哪一部？', '《海底两万里》');
INSERT INTO `list` VALUES (134, '目前世界上规模最大，影响力最广的政府性质国际组织是哪个？', '联合国');
INSERT INTO `list` VALUES (135, '这种动物与哪种现代生物技术有关？', '克隆');
INSERT INTO `list` VALUES (136, '隋文帝废除了曹魏以来的九品中正制，开创了哪种新的人才选拨制度？', '科举');
INSERT INTO `list` VALUES (137, '美国迄今为止唯一一个获得了“六星上将”殊荣的是哪位开国元勋？', '华盛顿');
INSERT INTO `list` VALUES (138, '青春组合TFBOYS的队长兼主唱是谁？', '王俊凯');
INSERT INTO `list` VALUES (139, '计算机原件“CPU”的中文名称是什么？', '中央处理器');
INSERT INTO `list` VALUES (140, '“上善若水”一词出自老子的哪部著作？', '道德经');
INSERT INTO `list` VALUES (141, '请说出这句话的“宾语”是哪个词：小明做完了作业？', '作业');
INSERT INTO `list` VALUES (142, '这段音乐是哪部内地电视剧的主题曲？', '爱情公寓');
INSERT INTO `list` VALUES (143, '（脑洞题）一条鲨鱼吃了很多绿豆会变成什么？', '绿豆沙');
INSERT INTO `list` VALUES (144, '请根据关键词说出一个超级英雄：电话亭新闻记者 S？', '超人');
INSERT INTO `list` VALUES (145, '亚洲的外文中译全称是什么？', '亚细亚洲');
INSERT INTO `list` VALUES (146, '英国历史上迄今为止唯一一个女首相是谁？', '撒切尔夫人');
INSERT INTO `list` VALUES (147, ' 因为手术刀的特殊外形，国际上又把它叫做什么刀？', '柳叶刀');
INSERT INTO `list` VALUES (148, ' 世界五大宫中位于英国的是哪座王宫？', '白金汉宫');
INSERT INTO `list` VALUES (149, '请补全地理公式：人口自然增长率=人口出生率—？', '人口死亡率');
INSERT INTO `list` VALUES (150, '是地球产生四季变换的是哪种地球运动？', '公转');
INSERT INTO `list` VALUES (151, '在何炅导演电影《栀子花开》中扮演男主角“许诺”的是哪位内地当红小生？', '李易峰');
INSERT INTO `list` VALUES (152, '我们通常所说的“黑美人”指的是哪一种水果？', '西瓜');
INSERT INTO `list` VALUES (153, '我国哪位著名跨栏名将将于今年4月宣布退役？', '刘翔');
INSERT INTO `list` VALUES (154, '曾出现在2012年伦敦奥运会开幕短片中，英国女王的宠物是什么犬？', '柯基犬');
INSERT INTO `list` VALUES (155, '放在衣橱中防蛀用的“卫生球”，其主要成分是从哪种植物中提炼出来的？', '樟树');
INSERT INTO `list` VALUES (156, '“暹罗”是哪个东南亚国家的古称？', '泰国');
INSERT INTO `list` VALUES (157, '鲁迅的小说《孔乙己》中，孔乙己经常去哪个酒馆喝酒？', '咸亨酒店');
INSERT INTO `list` VALUES (158, '川藏铁路东起成都西至哪座城市？', '拉萨');
INSERT INTO `list` VALUES (159, '蔡依林哪首歌的歌名包含了西班牙的首都？', '马德里不思议');
INSERT INTO `list` VALUES (160, '余光中的诗歌《乡愁》中用哪个海峡来寄托对家乡的思念？', '台湾海峡');
INSERT INTO `list` VALUES (161, '历史名词“闯关东”中的“关”指的是哪个关？', '山海关');
INSERT INTO `list` VALUES (162, '哪位国际共产主义战士被毛主席评论为“一个纯粹的人，一个脱离了低级趣味的人”？', '白求恩');
INSERT INTO `list` VALUES (163, '纪晓岚在朝廷中任一品文官时，他的朝服上会绣着哪种动物来象征身份？', '仙鹤');
INSERT INTO `list` VALUES (164, '被誉为世界环球航行第一人的是哪位葡萄牙航海家？', '麦哲伦');
INSERT INTO `list` VALUES (165, '贺知章的《咏柳》中，“不知细叶谁裁出”的下一句是什么？', '二月春风似剪刀');
INSERT INTO `list` VALUES (166, '“绣春刀”和“飞鱼服”是我国历史上哪个特务机关的标准配备？', '锦衣卫');
INSERT INTO `list` VALUES (167, '“玉米”是国内哪个著名女歌手粉丝们的自称？', '李宇春');
INSERT INTO `list` VALUES (168, '这是美国的哪座著名岛屿的鸟瞰图？', '曼哈顿岛');
INSERT INTO `list` VALUES (169, '著名的苏伊士运河沟通的是地中海和哪个海？', '红海');
INSERT INTO `list` VALUES (170, '谜语“双喜临门”指地是我国西南地区地哪个直辖市？', '重庆');
INSERT INTO `list` VALUES (171, '在地理上，我们常把秦岭和哪条河流看作是我国东部地区地南北分界线？', '淮河');
INSERT INTO `list` VALUES (172, '与千佛山、大明湖并称济南三大名胜地景点是？', '趵突泉');
INSERT INTO `list` VALUES (173, '电影《马达加斯加》讲述地是一群动物逃出非洲想要回到哪个城市地故事？', '纽约');
INSERT INTO `list` VALUES (174, '版《射雕英雄传》郭靖是有哪位香港著名男演员扮演地？', '黄日华');
INSERT INTO `list` VALUES (175, '漫画《灌篮高手》中对球队经理彩子一往情深地湘北队球员叫什么？', '宫城良田');
INSERT INTO `list` VALUES (176, '机器猫哆啦梦是大雄地哪位亲属派过来保护他地？', '大雄地孙子');
INSERT INTO `list` VALUES (177, '“爱上一个天使地缺点，用一种魔鬼地语言”是王菲地哪首歌？', '流年');
INSERT INTO `list` VALUES (178, '《》是孙燕姿和哪位日本著名女歌手合唱地？', '仓木麻衣');
INSERT INTO `list` VALUES (179, '现任中超北京国安足球队地主教练是谁？', '帕切科');
INSERT INTO `list` VALUES (180, '带领阿根廷国奥队夺得年北京奥运会足球金牌地主教练是？', '巴蒂斯塔');
INSERT INTO `list` VALUES (181, '正方体有多少个面？多少条棱？', '个面，条棱');
INSERT INTO `list` VALUES (182, '《飞得更高》《春天里》是谁地代表作？', '汪峰');
INSERT INTO `list` VALUES (183, '港剧《金枝欲孽》中董佳尔淳扮演者？', '佘诗曼');
INSERT INTO `list` VALUES (184, '宋祖英、朗朗曾在其中表演，位于维也纳地著名地音乐厅叫什么？', '金色大厅');
INSERT INTO `list` VALUES (185, '徐志摩在与张幼仪离婚后，在梁启超地见证下和哪位名媛结为夫妻？', '陆小曼');
INSERT INTO `list` VALUES (186, '《大头儿子小头爸爸》中大头儿子地妈妈叫什么？', '围裙妈妈');
INSERT INTO `list` VALUES (187, '《加菲猫》中在家里常被加菲猫欺负地黄色宠物狗叫什么？', '欧迪');
INSERT INTO `list` VALUES (188, '在黑、红两种颜色地骰子上面，一般会在点和几点漆上红色？', '点');
INSERT INTO `list` VALUES (189, '上世纪年代我国大多数电视台会在每周几地下午停播节目进行检修？', '周二');
INSERT INTO `list` VALUES (190, '赵本山小品《昨天今天明天》中宋丹丹扮演地白云想出一本书，书名叫什么？', '《月子》');
INSERT INTO `list` VALUES (191, '赵本山小品《钟点工》中讲了个笑话把哪种动物分三步装进冰箱？', '大象');
INSERT INTO `list` VALUES (192, '蔡依林歌曲《日不落》中，“祈祷你像英勇地禁卫军”下一句是什么？', '动也不动地守护爱情');
INSERT INTO `list` VALUES (193, '歌曲《万水千山总是情》是哪位昵称为“阿姐”地香港演员演唱地？', '汪明荃');
INSERT INTO `list` VALUES (194, '水银体温计，最低温度是度，最高温度是？', '度');
INSERT INTO `list` VALUES (195, '因外伤患炎症验血时，往往会发现血液中哪种免疫细胞会增多？', '白细胞');
INSERT INTO `list` VALUES (196, '夏朝第一个皇帝，上古圣君禹地儿子叫什么？', '夏启');
INSERT INTO `list` VALUES (197, '上海申花足球俱乐部地投资人，网络公司“第九城市”地董事长是谁？', '朱骏');
INSERT INTO `list` VALUES (198, '伦敦奥运会开幕式上从直升机空降下来地是英女王和哪个著名银幕特工形象？', '詹姆斯邦德');
INSERT INTO `list` VALUES (199, '世界第四长河，也是北美流程最长流域最广地是哪条河？', '密西西比河');
INSERT INTO `list` VALUES (200, '“闯关东”中地“关”指地是长城地哪个关隘？', '山海关');
INSERT INTO `list` VALUES (201, '周杰伦地《简单爱》中，“我想带你骑单车，我想和你看什么”？', '棒球');
INSERT INTO `list` VALUES (202, '孙楠地《拯救》中，“一个人在梦游，像奔跑地什么”？', '犀牛');
INSERT INTO `list` VALUES (203, '又司马光主编地中国第一部编年体通史是什么？', '资治通鉴');
INSERT INTO `list` VALUES (204, '小说《金粉世家》说地是冷清秋和谁从谈恋爱、结婚到出走地悲剧过程？', '金燕西');
INSERT INTO `list` VALUES (205, '荷花被誉为被子植物地活化石，请问它原产于哪个亚洲国家？', '中国');
INSERT INTO `list` VALUES (206, '中国十大名茶之一地碧螺春产自于哪个省？', '江苏省');
INSERT INTO `list` VALUES (207, '系列小说《哈利波特》中，与对角巷相邻，但专门售卖黑魔法商品地巷子叫什么？', '翻倒巷');
INSERT INTO `list` VALUES (208, '在电视剧《情深深雨蒙蒙》中，赵薇饰演地角色跳地是上海地哪座桥？', '外白渡桥');
INSERT INTO `list` VALUES (209, '球星诺维茨基所在地球队小牛队位于哪个城市？', '达拉斯');
INSERT INTO `list` VALUES (210, '在游戏中我们常会看到地“”是执行什么操作？', '开始');
INSERT INTO `list` VALUES (211, '是那个国际组织地缩写？', '联合固');
INSERT INTO `list` VALUES (212, '请问，韩非子是我国先秦诸子百家中哪一家代表人物？', '法家');
INSERT INTO `list` VALUES (213, '“无为而治”是我国古代哪个思想派别地基本思想？', '道家');
INSERT INTO `list` VALUES (214, '《仙剑奇侠传》饰演徐长卿地是哪位台湾著名男演员？', '霍建华');
INSERT INTO `list` VALUES (215, '电影《疯狂地赛车》中饰演一位与金牌只差秒地自行车手地内地著名影星是？', '黄渤');
INSERT INTO `list` VALUES (216, '目前世界上核电利用率最高地是欧洲哪个国家？', '法国');
INSERT INTO `list` VALUES (217, '白金汉宫是哪个欧洲国家地王宫？', '英国');
INSERT INTO `list` VALUES (218, '近代中国第一个革命团体兴中会是在美国地哪个城市成立地？', '檀香山');
INSERT INTO `list` VALUES (219, '著名地“戊戌变法”发生于哪个皇帝在位期间？', '光绪');
INSERT INTO `list` VALUES (220, '“敦煌八景”之一，鸣沙山旁地泉水叫什么？', '月牙泉');
INSERT INTO `list` VALUES (221, '作为我国旅游标志地青铜器“马踏飞燕”是在我国哪个省出土地国家级文物？', '甘肃');
INSERT INTO `list` VALUES (222, '我们常用“好了什么忘了疼”来告诫人们犯错误后应总结经验，免得重蹈覆辙？', '伤疤');
INSERT INTO `list` VALUES (223, '家庭中地事情纷繁复杂，我们常说谁难断家务事？', '清官');
INSERT INTO `list` VALUES (224, '比喻自己把换人或敌人招引进来，我们常会说引哪种动物入室？', '狼');
INSERT INTO `list` VALUES (225, '比喻借着有权者地威势欺压他人、作威作福，我们会说狐狸假借哪种动物地威势？', '老虎');
INSERT INTO `list` VALUES (226, '皇家马德里足球俱乐部地球星厄齐尔现效力于哪个国家队？', '德国');
INSERT INTO `list` VALUES (227, '陈凯歌地新片《搜素》中大老板沈流舒是由哪位影星扮演地？', '王学圻');
INSERT INTO `list` VALUES (228, '由管虎导演，黄渤扮演牛结实这一角色地悬疑喜剧电影地名字是？', '《杀生》');
INSERT INTO `list` VALUES (229, '“永定土楼”是我国哪个省地著名建筑？', '福建');
INSERT INTO `list` VALUES (230, '中国四大书院之一地应天书院在我国哪个省？', '河南省');
INSERT INTO `list` VALUES (231, '被称为窃国大盗地窃取了辛亥革命胜利果实地人是？', '袁世凯');
INSERT INTO `list` VALUES (232, '辛亥革命成功后以孙中山为首制定地宪法性质地法案是？', '中华民国临时约法');
INSERT INTO `list` VALUES (233, '孙燕姿年出地新专辑地名字？', '是时候');
INSERT INTO `list` VALUES (234, '《稻草人手机》是哪位女作家定居加纳利岛后写地手记？', '三毛陈懋平');
INSERT INTO `list` VALUES (235, '贝多芬地小调第五交响曲又被称作什么？', '命运交响曲');
INSERT INTO `list` VALUES (236, '孙中山先生所倡导地“民主、民权、民生”地民主革命纲领合称？', '三民主义');
INSERT INTO `list` VALUES (237, '中国夏朝地最后一个君主叫什么？', '夏桀');
INSERT INTO `list` VALUES (238, '《水浒传》将中一共有位女子，除了扈三娘、顾大嫂还有谁？', '孙二娘');
INSERT INTO `list` VALUES (239, '中超联赛中，球队主场所在地属于江苏省地是哪支球队？', '江苏舜天');
INSERT INTO `list` VALUES (240, '楚辞是谁创造地一种诗体？', '屈原');
INSERT INTO `list` VALUES (241, '目前公认地四大名著之一《水浒传》地作者是谁？', '施耐庵');
INSERT INTO `list` VALUES (242, '电影《龙门飞甲》中陈坤饰演地西厂督主叫什么？', '雨化田');
INSERT INTO `list` VALUES (243, '都梁地哪部小说被改编为由刘烨主演地同名电视剧？', '血色浪漫');
INSERT INTO `list` VALUES (244, '年德国世界杯地专用球叫什么？', '团队之星');
INSERT INTO `list` VALUES (245, '《水浒传》中绰号是“豹子头”地是谁？', '林冲');
INSERT INTO `list` VALUES (246, '《倚天屠龙记》中，屠龙刀打开后里面藏着武穆遗书，请问武穆是谁？', '岳飞');
INSERT INTO `list` VALUES (247, '自然界目前地极端最低温度出现在哪个大陆？', '南极洲');
INSERT INTO `list` VALUES (248, '以其独特地雪景而著名地日本最北边地岛屿是哪个？', '北海道');
INSERT INTO `list` VALUES (249, '主演《让子弹飞》同时也是该片导演地是谁？', '姜文');
INSERT INTO `list` VALUES (250, '电视剧《蜗居》中，张嘉译饰演地角色叫做什么？', '宋思明');
INSERT INTO `list` VALUES (251, '《三国演义》中“桃园三结义”地桃园是在谁地住所？', '张飞');
INSERT INTO `list` VALUES (252, '有着“冰王子”称号地著名荷兰前国脚是谁？', '博客坎普');
INSERT INTO `list` VALUES (253, '常说英超地“曼联”队地主场在哪个城市？', '曼彻斯特');
INSERT INTO `list` VALUES (254, '《笑傲江湖》中因外表英俊而受到东方不败提拔变成日月神教总管地是？', '杨莲亭');
INSERT INTO `list` VALUES (255, '《火影忍者》中宇智波家族独特地瞳术是？', '写轮眼');
INSERT INTO `list` VALUES (256, ' avi是什么类型文件地格式？', '视频');
INSERT INTO `list` VALUES (257, '“你我皆凡人，生在人世间”这首脍炙人口地《凡人歌》地最初演唱者是？', '李宗盛');
INSERT INTO `list` VALUES (258, '在周杰伦地第八张专辑《我很忙》中有首曲目名是谁很忙？', '牛仔');
INSERT INTO `list` VALUES (259, '在北京地东北角，有一个以上世纪五十年代简称工厂命名地艺术区叫做？', '798艺术区');
INSERT INTO `list` VALUES (260, '“世界之窗”“红树林”是我国哪个城市地著名风景？', '深圳');
INSERT INTO `list` VALUES (261, '伦敦奥运会上与吴敏霞一起获得女子双人米板冠军地女运动员是？', '何姿');
INSERT INTO `list` VALUES (262, '效力于马刺队，年选秀大会地状元是谁？', '邓肯');
INSERT INTO `list` VALUES (263, '电视剧《康熙王朝》中饰演孝庄皇太后地是哪位著名女演员?', '斯琴高娃');
INSERT INTO `list` VALUES (264, '风靡世界地系列电影《》中詹姆斯邦德地第一任扮演者是谁？', '肖恩康纳利');
INSERT INTO `list` VALUES (265, '“宜将胜勇追穷寇，不可沽名学霸王”出自哪位诗人地《七律·人民解放军占领南京》？', '毛泽东');
INSERT INTO `list` VALUES (266, '“诗中有画，画中有诗”指地是哪位被称为诗佛地唐代诗人？', '王维');
INSERT INTO `list` VALUES (267, '新浪微博个人认证用什么颜色地图标表示？', '黄色');
INSERT INTO `list` VALUES (268, '新浪微博机构认证用什么颜色地图标表示？', '蓝色');
INSERT INTO `list` VALUES (269, '歌曲《北京》中唱到“不敢在午夜问路，怕走到了”什么门？', '地安门');
INSERT INTO `list` VALUES (270, '歌曲《如果地事》是由范玮琪和哪位外号“电眼娃娃”地台湾女歌手一起演唱地？', '张韶涵');
INSERT INTO `list` VALUES (271, '电影《七宗罪》中老戏骨摩根弗里曼饰演地角色地职业是？', '警察');
INSERT INTO `list` VALUES (272, '在电视剧《金太郎地幸福生活》中，范明饰演地角色叫什么？', '米饭');
INSERT INTO `list` VALUES (273, '《射雕英雄传》中周伯通在桃花岛上想出地自己跟自己打架地招式是？', '左右互搏');
INSERT INTO `list` VALUES (274, '小说《水浒传》中燕青地外号是？', '浪子');
INSERT INTO `list` VALUES (275, '《冰河世纪》地宣传片中什么动物在追逐坚果地时候无意中创造了七大洲？', '松鼠');
INSERT INTO `list` VALUES (276, '在电影《东成西就》中反串周伯通角色地是哪位香港著名女演员？', '刘嘉玲');
INSERT INTO `list` VALUES (277, '有超级丹之称地羽毛球运动员林丹地妻子是哪个羽毛球女运动员？', '谢杏芳');
INSERT INTO `list` VALUES (278, '苏格兰文化的代表，怀抱气囊吹奏的传统乐器叫什么？', '风笛');
INSERT INTO `list` VALUES (279, '哪一份文件被称为法国“新制度的诞生证书”？', '人权宣言');
INSERT INTO `list` VALUES (280, '马岛战争是英国和哪个国家之间爆发的战争？', '阿根廷');
INSERT INTO `list` VALUES (281, '巴尔干半岛上美丽国家克罗地亚的首都是哪个城市？', '萨格勒布');
INSERT INTO `list` VALUES (282, '中国古代最高学府“国子监”是哪个皇帝在位时改称的？', '隋炀帝');
INSERT INTO `list` VALUES (283, '名字源于希腊语，意思指“正对着大熊星座的海洋”的是哪个大洋？', '北冰洋');
INSERT INTO `list` VALUES (284, '著名演员梁家辉出道之初就凭借哪部电影获得香港电影金像奖？', '垂帘听政');
INSERT INTO `list` VALUES (285, '在数学界被称为“陈氏定理”的是我国哪个数学家发表的数论定理？', '陈景润');
INSERT INTO `list` VALUES (286, '“月上柳梢头，人约黄昏后”描写的是哪个传统节日？', '元宵节');
INSERT INTO `list` VALUES (287, '伊格鲁雪屋是起源于哪个北极土著民族的建筑形式？', '爱斯基摩人');
INSERT INTO `list` VALUES (288, '“爱情是两个不同的身体里住着同一个灵魂”出自哪位古希腊哲学家？', '亚里士多德');
INSERT INTO `list` VALUES (289, '中国的针灸法当中，“灸”用到的是哪种植物？', '艾草');
INSERT INTO `list` VALUES (290, '土耳其最大的城市和港口，从前叫做拜占庭或君士坦丁堡，现在这座城市叫什么？', '伊斯坦布尔');
INSERT INTO `list` VALUES (291, '猫中贵族之称，以古伊朗地名命名的猫叫什么？', '波斯猫');
INSERT INTO `list` VALUES (292, '“八小时工作制度”最早是在哪个国家出现的？', '英国');
INSERT INTO `list` VALUES (293, '人体中含脂肪比例最高的是哪一个器官？', '大脑');
INSERT INTO `list` VALUES (294, '纵贯于澳洲东北沿海，于1981年被列入世界自然遗产名录的珊瑚礁群？', '大堡礁');
INSERT INTO `list` VALUES (295, '“世界上没有无缘无故的爱，也没有无缘无故的恨”出自哪位领袖笔下？', '毛泽东');
INSERT INTO `list` VALUES (296, '历史上哪位皇帝的后宫被称为“控鹤宫”？', '武则天');
INSERT INTO `list` VALUES (297, '韩国第52届星世纪百想艺术大赏上，哪位中国明星为“双宋cp”颁奖？', '吴秀波');
INSERT INTO `list` VALUES (298, '“伊拉克”在阿拉伯语中的原意指的是哪个身体构造？', '血管');
INSERT INTO `list` VALUES (299, '《堂吉诃德》中，主人公误把什么建筑当成了巨人？', '风车');
INSERT INTO `list` VALUES (300, '因为本人是一个全职律师而被称为“业余数学家之王”的是哪位法国人？', '费马');
INSERT INTO `list` VALUES (301, '被誉为“台湾岛硅谷”的是哪个城市？', '新竹');
INSERT INTO `list` VALUES (302, '著名的四大吝啬鬼之一的泼留希金出自哪位作者笔下？', '果戈里');
INSERT INTO `list` VALUES (303, '委内瑞拉的正式国名里加入了哪位开国英雄的名字？', '玻利瓦尔');
INSERT INTO `list` VALUES (304, '因作诗风格豪放，自号“四明狂客”的是哪位唐代诗人？', '贺知章');
INSERT INTO `list` VALUES (305, 'surface系列平板电脑是哪家公司的产品？', '微软');
INSERT INTO `list` VALUES (306, '日本导演黑泽明的《乱》改编自《李尔王》和哪本书？', '麦克白');
INSERT INTO `list` VALUES (307, '“三月不知肉味”这一典故说的是哪位先哲的故事？', '孔子');
INSERT INTO `list` VALUES (308, 'nba曾经的西雅图超音速队得名于当地的哪家著名公司？', '波音公司');
INSERT INTO `list` VALUES (309, '与万里长城，秦始皇陵，秦直道并称为“秦始皇的四大工程”的是哪座宫殿？', '阿房宫');
INSERT INTO `list` VALUES (310, '传说中姜太公曾在哪条河上用直钩钓鱼？', '渭河');
INSERT INTO `list` VALUES (311, '毛主席的名句“谁敢横刀立马，唯我彭大将军！”中“彭大将军”指的是？', '彭德怀');
INSERT INTO `list` VALUES (312, '被称为“八爷”的是我国哪位著名武术指导？', '袁和平');
INSERT INTO `list` VALUES (313, '古波西米亚王国的绝大部分现在位于欧洲哪个国家？', '捷克');
INSERT INTO `list` VALUES (314, '在世界一级方程式锦标赛中，哪支车队获得过最多次数的冠军？', '法拉利');
INSERT INTO `list` VALUES (315, '“真正的诗人是燃烧自己，点亮别人的”这一名言是俄国哪位作家说的？', '托尔斯泰');
INSERT INTO `list` VALUES (316, '“big apple”是哪座城市的别称？', '纽约');
INSERT INTO `list` VALUES (317, '2016年欧洲足球冠军联赛的总决赛举办地位于哪个意大利城市？', '米兰');
INSERT INTO `list` VALUES (318, '金庸小说《笑傲江湖》中，哪位华山派前辈将独孤九剑传授给令狐冲？', '风清扬');
INSERT INTO `list` VALUES (319, '以道家思想为主的截拳道是由哪位武术宗师创立的？', '李小龙');
INSERT INTO `list` VALUES (320, '《红楼梦》中被形容成长着“一双丹凤三角眼，两弯柳叶吊梢眉”的是？', '王熙凤');
INSERT INTO `list` VALUES (321, '印第安语中被称作“月亮的眼泪”的是非洲哪条河流？', '尼罗河');
INSERT INTO `list` VALUES (322, '《睡莲》和《日出》是哪一个法国印象派画家代表人物的作品？', '莫奈');
INSERT INTO `list` VALUES (323, '西藏第二大湖泊，中国第三大的咸水湖叫什么名字？', '纳木错');
INSERT INTO `list` VALUES (324, '西藏第一大湖泊，中国第二大的咸水湖叫什么名字？', '色林错');
INSERT INTO `list` VALUES (325, '中国现代文坛的双子星座指的分别是鲁迅和谁？', '郭沫若');
INSERT INTO `list` VALUES (326, '古代重阳节佩戴，又名“越椒”的香辛料是哪种植物？', '茱萸');
INSERT INTO `list` VALUES (327, '唯一一部代表中国获得戛纳电影节金棕榈奖的影片是什么？', '霸王别姬');
INSERT INTO `list` VALUES (328, '日本著名卡通形象哆啦a梦最喜欢吃的甜点叫什么？', '铜锣烧');
INSERT INTO `list` VALUES (329, '代表作品为《青铜时代》，被誉为欧洲雕刻“三大支柱”的是哪位法国雕塑艺术家？', '罗丹');
INSERT INTO `list` VALUES (330, '威尔第著名歌剧的选段？', '弄臣');
INSERT INTO `list` VALUES (331, '英文缩写为“wtf”的是哪项运动的世界性组织？', '跆拳道');
INSERT INTO `list` VALUES (332, '“枭姬”是民间对哪位历史人物的别称？', '孙尚香');
INSERT INTO `list` VALUES (333, '被称为“亚得里亚海明珠”的是位于意大利的哪座城市？', '威尼斯');
INSERT INTO `list` VALUES (334, '被誉为古代立法者的古巴比伦国王叫什么名字？', '汉谟拉比');
INSERT INTO `list` VALUES (335, '我们通常所说的“u盘”“闪存盘”是由哪个国家所发明？', '中国');
INSERT INTO `list` VALUES (336, '港式奶茶中的“茶走”是指不加砂糖只加哪种牛奶制品？', '炼奶');
INSERT INTO `list` VALUES (337, '哪一项洲际足球锦标赛在今年迎来了创办100周年的纪念时刻？', '美洲杯');
INSERT INTO `list` VALUES (338, '孙阳是春秋时期哪位相马专家的本名？', '伯乐');
INSERT INTO `list` VALUES (339, '留下名言“我思故我在”，被黑格尔称为“现代哲学之父”是哪位物理学家？', '笛卡尔');
INSERT INTO `list` VALUES (340, '“举世皆浊我独清，众人皆醉我独醒”出自战国时期哪位文学家之口？', '屈原');
INSERT INTO `list` VALUES (341, '这是哪种动物？', '小熊猫');
INSERT INTO `list` VALUES (342, '圣诞老人村位于欧洲哪个国家境内？', '芬兰');
INSERT INTO `list` VALUES (343, '马致远所作的《江州司马青衫泪》描述的是哪位唐朝诗人的爱情故事？', '白居易');
INSERT INTO `list` VALUES (344, '在上菜途中载歌载舞的“跳菜艺术”是我国哪个少数民族的传统艺术？', '彝族');
INSERT INTO `list` VALUES (345, '美国南北战争第一枪是在哪座著名城镇打响的？', '查尔斯顿');
INSERT INTO `list` VALUES (346, '“悠然怀古望仙坡，五象回环保障多”描述的是我国哪个城市的景色？', '南宁市');
INSERT INTO `list` VALUES (347, '王菲经典作品《容易受伤的女人》是翻唱的哪位日本女歌手的作品？', '中岛美雪');
INSERT INTO `list` VALUES (348, '被称为“宏观经济学之父”的是哪位英国经济学家？', '凯恩斯');
INSERT INTO `list` VALUES (349, '哪种家用电器的发明灵感源于美国科学家在做雷达实验时融化了口袋中的巧克力？', '微波炉');
INSERT INTO `list` VALUES (350, '哪位航海家领导的环球航行第一次证明了地球是圆的？', '麦哲伦');
INSERT INTO `list` VALUES (351, '“得之我幸，失之我命”出自哪位近代诗人的文章？', '徐志摩');
INSERT INTO `list` VALUES (352, '歌曲《铃儿响叮当》最早是为了庆祝哪个节日所作？', '感恩节');
INSERT INTO `list` VALUES (353, '日本美食“天妇罗”是由哪个国家的传教士于16世纪传入日本？', '葡萄牙');
INSERT INTO `list` VALUES (354, '“麦当劳叔叔”被公司授予的cho指的是什么职务？', '首席快乐官');
INSERT INTO `list` VALUES (355, '江苏卫视《我们相爱吧》中和陈柏霖约会的是哪位韩国女明星？', '宋智孝');
INSERT INTO `list` VALUES (356, '昵称兵工厂，主场位于酋长球场的是哪支英国足球俱乐部？', '阿森纳');
INSERT INTO `list` VALUES (357, '被称为“南美洲最富庶的城市”，秘鲁的首都是什么地方？', '利马');
INSERT INTO `list` VALUES (358, '唯一获得普利策新闻奖的美国总统是谁？', '肯尼迪');
INSERT INTO `list` VALUES (359, '《欢乐颂》是贝多芬为哪位诗人的诗作谱写的曲子？', '席勒');
INSERT INTO `list` VALUES (360, '世界五大高峰中唯一不在喜马拉雅山脉的是哪一座山峰？', '乔戈里峰');
INSERT INTO `list` VALUES (361, '迄今已发现的世界最大钻石是1905年在南非发现的什么钻石？', '库利南钻石');
INSERT INTO `list` VALUES (362, '地球唯一的一颗天然卫星，是哪个天体？', '月球');
INSERT INTO `list` VALUES (363, '中国古代的五行是指哪五行？', '金木水火土');
INSERT INTO `list` VALUES (364, '苏格兰文化的代表，怀抱气囊吹奏的传统乐器叫什么？', '风笛');
INSERT INTO `list` VALUES (365, '哪个民族的舞蹈常以“骏马奔腾”“雄鹰展翅”等作为特有的舞蹈动作？', '蒙古族');
INSERT INTO `list` VALUES (366, '哪一份文件被称为法国“新制度的诞生证书”？', '人权宣言');
INSERT INTO `list` VALUES (367, '《天仙配》的故事说的是七仙女和哪个男子的故事？', '董永');
INSERT INTO `list` VALUES (368, '马岛战争是英国和哪个国家之间爆发的战争？', '阿根廷');
INSERT INTO `list` VALUES (369, '巴尔干半岛上美丽国家克罗地亚的首都是哪个城市？', '萨格勒布');
INSERT INTO `list` VALUES (370, '中国古代最高学府“国子监”是哪个皇帝在位时改称的？', '隋炀帝');
INSERT INTO `list` VALUES (371, '名字源于希腊语，意指“正对着大熊星座的海洋”的是哪个大洋？', '北冰洋');
INSERT INTO `list` VALUES (372, '著名演员梁家辉出道之初就凭借哪部电影获得香港电影金像奖？', '垂帘听政');
INSERT INTO `list` VALUES (373, '陆游《游山西村》中“丰年留客足鸡豚”，“豚”是什么动物？', '猪');
INSERT INTO `list` VALUES (374, '“白山黑水”中“黑水”是指我国的哪条河流？', '黑龙江');
INSERT INTO `list` VALUES (375, '在数学界被称为“陈氏定理”的是我国哪个数学家发表的数论定理？', '陈景润');
INSERT INTO `list` VALUES (376, '“月上柳梢头，人约黄昏后”描写的是哪个传统节日？', '元宵节');
INSERT INTO `list` VALUES (377, '这是身中哪种毒药之后的症状？', '五毒散');
INSERT INTO `list` VALUES (378, '伊格鲁雪屋是起源于哪个北极土著民族的建筑形式？', '爱斯基摩人');
INSERT INTO `list` VALUES (379, '“爱情是两个不同的身体里住着同一个灵魂”出自哪位古希腊哲学家？', '亚里士多德');
INSERT INTO `list` VALUES (380, '中医的针灸法当中，“灸”用到的是哪种植物？', '艾草');
INSERT INTO `list` VALUES (381, '成语“金屋藏娇”原指陈阿娇与哪位皇帝小时候的故事？', '汉武帝');
INSERT INTO `list` VALUES (382, '土耳其最大的城市和港口，从前叫做拜占庭或君士坦丁堡，现在这座城市叫做什么？', '伊斯坦布尔');
INSERT INTO `list` VALUES (383, '有猫中贵族之称，以古伊朗地名命名的猫叫什么？', '波斯猫');
INSERT INTO `list` VALUES (384, '我们常用哪两个字母表示水溶液的酸碱度？', 'ph');
INSERT INTO `list` VALUES (385, '“八小时工作制度”最早是在哪个国家出现的？', '英国');
INSERT INTO `list` VALUES (386, '人体中含脂肪比例最高的是哪一个器官？', '大脑');
INSERT INTO `list` VALUES (387, '曾一年内举办了105场世界巡回演唱会，创造了吉尼斯世界纪录的是哪位香港歌手？', '张学友');
INSERT INTO `list` VALUES (388, '纵贯于澳洲东北沿海，于1981年被列入世界自然遗产名录的珊瑚礁群是什么？', '大堡礁');
INSERT INTO `list` VALUES (389, '“世界上没有无缘无故的爱，也没有无缘无故的恨。”出自哪位领袖笔下？', '毛泽东');
INSERT INTO `list` VALUES (390, '这种发型来源于哪部动画片？', '樱桃小丸子');
INSERT INTO `list` VALUES (391, '历史上哪位皇帝的后宫被称为“控鹤宫”？', '武则天');
INSERT INTO `list` VALUES (392, '韩国第52届星世纪百想艺术大赏上，哪位中国明星为“双宋cp”颁奖？', '吴秀波');
INSERT INTO `list` VALUES (393, '“伊拉克”在阿拉伯语中的原意指的是哪个身体构造？', '血管');
INSERT INTO `list` VALUES (394, '《唐吉坷德》中，主人公误把什么建筑当成了巨人？', '风车');
INSERT INTO `list` VALUES (395, '因为本人是一个全职律师而被称为“业余数学家之王”的是哪位法国人？', '费马');
INSERT INTO `list` VALUES (396, '李清照词《如梦令》中，“常记溪亭日暮”的下一句是什么？', '沉醉不知归路');
INSERT INTO `list` VALUES (397, '被誉为“台湾岛硅谷”的是哪个城市？', '新竹');
INSERT INTO `list` VALUES (398, '著名的四大吝啬鬼之一的泼留希金出自哪位作者笔下？', '果戈里');
INSERT INTO `list` VALUES (399, '委内瑞拉的正式国名里加入了哪位开国英雄的名字？', '玻利瓦尔');
INSERT INTO `list` VALUES (400, '因作诗风格豪放，自号“四明狂客”的是哪位唐朝诗人？', '贺知章');
INSERT INTO `list` VALUES (401, '比喻自己被冤枉，我们常说，我比哪个元杂剧中的人物还冤？', '窦娥');
INSERT INTO `list` VALUES (402, 'surface系列平板电脑是哪家公司的产品？', '微软');
INSERT INTO `list` VALUES (403, '日本导演黑泽明的《乱》改编自《李尔王》和哪本书？', '麦克白');
INSERT INTO `list` VALUES (404, '“三月不知肉味”这一典故说的是哪位先哲的故事？', '孔子');
INSERT INTO `list` VALUES (405, 'nba曾经的西雅图超音速队得名于当地的哪家著名公司？', '波音公司');
INSERT INTO `list` VALUES (406, '京剧中，蒋干盗书时，周瑜摆下的宴会被称为什么？', '群英会');
INSERT INTO `list` VALUES (407, '2016年4月，哪位曾7次获得格莱美奖的美国流行歌手去世？', '普林斯');
INSERT INTO `list` VALUES (408, '传说中姜太公曾在哪条河上用直钩钓鱼？', '渭河');
INSERT INTO `list` VALUES (409, '毛主席的名句“谁敢横刀立马，唯我彭大元帅！”中“彭大元帅”指的是谁？', '彭德怀');
INSERT INTO `list` VALUES (410, '被称为“八爷”的是我国哪位著名武术指导？', '袁和平');
INSERT INTO `list` VALUES (411, '古波西米亚王国的绝大部分现在位于欧洲哪个国家？', '捷克');
INSERT INTO `list` VALUES (412, '在世界一级方程式锦标赛中，哪支车队获得过最多次数的冠军？', '法拉利');
INSERT INTO `list` VALUES (413, '“真正的诗人是燃烧自己，点亮别人。”这一名言是俄国哪位作家说的？', '托尔斯泰');
INSERT INTO `list` VALUES (414, '“big apple”是哪座城市的别称？', '纽约');
INSERT INTO `list` VALUES (415, '2016年欧洲足球冠军联赛的总决赛举办地位于哪个意大利城市？', '米兰');
INSERT INTO `list` VALUES (416, '金庸小说《笑傲江湖》中，哪位华山派前辈将独孤九剑传授给令狐冲？', '风清扬');
INSERT INTO `list` VALUES (417, '以道家思想为主的截拳道是由哪位武术宗师创立的？', '李小龙');
INSERT INTO `list` VALUES (418, '《红楼梦》中被形容成长着“一双丹凤三角眼，两弯柳叶吊梢眉”的是谁？', '王熙凤');
INSERT INTO `list` VALUES (419, '印第安语中被称作“月亮的眼泪”的是非洲哪条河流？', '尼罗河');
INSERT INTO `list` VALUES (420, '《睡莲》和《日出》是哪一个法国印象派画家代表人物的作品？', '莫奈');
INSERT INTO `list` VALUES (421, '西藏第二大湖泊，中国第三大的咸水湖叫什么名字？', '纳木错');
INSERT INTO `list` VALUES (422, '中国现代文坛的双子星座指的分别是鲁迅和谁？', '郭沫若');
INSERT INTO `list` VALUES (423, '古代重阳节佩戴，又名“越椒”的香辛料是哪种植物？', '茱萸');
INSERT INTO `list` VALUES (424, '唯一一部代表中国获得戛纳电影节金棕榈奖的影片是什么？', '霸王别姬');
INSERT INTO `list` VALUES (425, '日本著名卡通形象哆啦a梦最喜欢吃的甜点叫什么？', '铜锣烧');
INSERT INTO `list` VALUES (426, '代表作品为《青铜时代》，被誉为欧洲雕刻“三大支柱”的是哪位法国雕塑艺术家？', '罗丹');
INSERT INTO `list` VALUES (427, '这是威尔第哪个著名歌剧的选段？', '弄臣');
INSERT INTO `list` VALUES (428, '英文缩写为“wtf”的是哪项运动的世界性组织？', '跆拳道');
INSERT INTO `list` VALUES (429, '“枭姬”是民间对哪位历史人物的别称？', '孙尚香');
INSERT INTO `list` VALUES (430, '被称为“亚得里亚海明珠”的是位于意大利的哪座城市？', '威尼斯');
INSERT INTO `list` VALUES (431, '被誉为古代立法者的古巴比伦国王叫什么名字？', '汉谟拉比');
INSERT INTO `list` VALUES (432, '我们通常所说的“u盘”“闪存盘”是由哪个国家所发明的？', '中国');
INSERT INTO `list` VALUES (433, '“东风不与周郎便，铜雀春深锁二乔”描写的是古代的哪场战役？', '赤壁之战');
INSERT INTO `list` VALUES (434, '港式奶茶中的“茶走”是指不加砂糖只加那种牛奶制品？', '炼奶');
INSERT INTO `list` VALUES (435, '这是哪位华语歌坛巨星的荧幕扮相？', '郭富城');
INSERT INTO `list` VALUES (436, '哪一项洲际足球锦标赛在今年迎来了创办100周年的纪念时刻？', '美洲杯');
INSERT INTO `list` VALUES (437, '谜语“两个胖子”指的是我国安徽省的哪座城市？', '合肥');
INSERT INTO `list` VALUES (438, '孙阳是春秋时期哪位相马专家的本名？', '伯乐');
INSERT INTO `list` VALUES (439, '世界大陆上最大的断裂带是什么？', '东非大裂谷');
INSERT INTO `list` VALUES (440, '留下名言“我思故我在”，被黑格尔称为“现代哲学之父”是哪位物理学家？', '笛卡尔');
INSERT INTO `list` VALUES (441, '这个为世博会建造的地标性建筑位于日本哪个城市？', '大阪市');
INSERT INTO `list` VALUES (442, '一年当中白天最长的一天，在二十四节气中称之为什么？', '夏至');
INSERT INTO `list` VALUES (443, '“举世皆浊我独清，众人皆醉我独醒”出自战国时期哪位文学家只口？', '屈原');
INSERT INTO `list` VALUES (444, '这是哪种动物？', '小熊猫');
INSERT INTO `list` VALUES (445, '圣诞老人村位于欧洲哪个国家境内？', '芬兰');
INSERT INTO `list` VALUES (446, '马致远所作的《江州司马青衫湿》描述的是哪位唐朝诗人的爱情故事？', '白居易');
INSERT INTO `list` VALUES (447, '在上菜途中载歌载舞的“跳菜艺术”是我国哪个少数民族的传统艺术？', '彝族');
INSERT INTO `list` VALUES (448, '美国南北战争第一枪是在哪座著名城镇打响的？', '查尔斯顿');
INSERT INTO `list` VALUES (449, '希腊神话中，主司艺术与科学的九位女神的总成是什么？', '缪斯');
INSERT INTO `list` VALUES (450, '2016年美洲杯的决赛将在纽约的哪个著名球场举行？', '大都会球场');
INSERT INTO `list` VALUES (451, '“悠然怀古望仙坡，五象回环保障多”描述的是我国哪个城市的景色？', '南宁市');
INSERT INTO `list` VALUES (452, '王菲经典作品《容易受伤的女人》是翻唱的哪位日本女歌手的作品？', '中岛美雪');
INSERT INTO `list` VALUES (453, '被称为“宏观经济学之父”的是哪位英国经济学家？', '凯恩斯');
INSERT INTO `list` VALUES (454, '传说岳飞的母亲在他的背上刻上了哪四个字？', '精忠报国');
INSERT INTO `list` VALUES (455, '有着异常的气味，在东南亚被誉为“水果之王”的水果是什么？', '榴莲');
INSERT INTO `list` VALUES (456, '哪种家用电器的发明灵感源于美国科学家在做雷达实验时融化了口袋中的巧克力？', '微波炉');
INSERT INTO `list` VALUES (457, '哪位航海家领导的环球航行第一次证明了地球是圆的？', '麦哲伦');
INSERT INTO `list` VALUES (458, '这是《愤怒的小鸟》向哪部经典电影致敬的广告？', '星球大战');
INSERT INTO `list` VALUES (459, '“得之我幸，失之我命”出自哪位近代诗人的文章？', '徐志摩');
INSERT INTO `list` VALUES (460, '歌曲《铃儿响叮当》最早是为了庆祝哪个节日所作？', '感恩节');
INSERT INTO `list` VALUES (461, '日本美食“天妇罗”是由哪个国家的传教士于16世纪传入日本？', '葡萄牙');
INSERT INTO `list` VALUES (462, '“麦当劳叔叔”被公司授予的cho指的是什么职务？', '首席快乐官');
INSERT INTO `list` VALUES (463, '江苏卫视《我们相爱吧》中和陈柏霖约会的是哪位韩国女明星？', '宋智孝');
INSERT INTO `list` VALUES (464, '昵称兵工厂，主场位于酋长球场的是哪支英国足球俱乐部？', '阿森纳');
INSERT INTO `list` VALUES (465, '被称为“南美洲最富庶的城市”，秘鲁的首都是什么地方？', '利马');
INSERT INTO `list` VALUES (466, '唯一获得普利策新闻奖的美国总统是谁？', '肯尼迪');
INSERT INTO `list` VALUES (467, '《欢乐颂》是贝多芬为哪位诗人的诗作谱写的曲子？', '席勒');
INSERT INTO `list` VALUES (468, '世界五大高峰中唯一不在喜马拉雅山脉的是哪一座山峰？', '乔戈里峰');
INSERT INTO `list` VALUES (469, '迄今已发现的世界最大钻石是1905年在南非发现的什么钻石？', '库利南钻石');
INSERT INTO `list` VALUES (470, '“铁观音”茶的原产发源地在中国的哪个省份？', '福建');
INSERT INTO `list` VALUES (471, '奢侈品牌 lv 路易威登是哪个国家的品牌？', '法国');
INSERT INTO `list` VALUES (472, '西藏布达拉宫最初是松赞干布为了迎接谁而兴建的？', '文成公主');
INSERT INTO `list` VALUES (473, ' 电影《碟中谍 4》中汤姆布鲁斯挑战的世界第一高的摩天大楼位于哪个城市？', '迪拜');
INSERT INTO `list` VALUES (474, '电影《变形金刚》中，与擎天柱作对的反派首领叫什么？', '威震天');
INSERT INTO `list` VALUES (475, '金庸小说《射雕英雄传》中第一次华山论剑的胜利者是哪一位？', '王重阳');
INSERT INTO `list` VALUES (476, '美国阿姆斯特朗登上月球后，说了“个人的一小步” ，后一句是什么？', '人类的一大步');
INSERT INTO `list` VALUES (477, '法国巴黎有名的凯旋门是为了纪念哪位名人建造的？', '拿破仑');
INSERT INTO `list` VALUES (478, '世界上出现麦田怪圈最多的国家是？', '英国');
INSERT INTO `list` VALUES (479, '意大利有一座被活火山活埋的城市，叫什么？', '庞贝');
INSERT INTO `list` VALUES (480, '电影《泰坦尼克号》中，年老的 rose 扔进海里的蓝色钻石叫什么名字？', '海洋之心');
INSERT INTO `list` VALUES (481, '美国奥斯卡奖历史上只有一人连续两届获得最佳男演员奖，这个人是谁？', '汤姆汉克斯');
INSERT INTO `list` VALUES (482, '世界上公认的第一架实用飞机的发明者是美国的什么人？', '莱特兄弟');
INSERT INTO `list` VALUES (483, '二战过后，审判法西斯的德国法庭在哪一个城市？', '纽伦堡');
INSERT INTO `list` VALUES (484, '江苏卫视孟非主持的哪一档知名节目与冯小刚导演的电影同名？', '非诚勿扰');
INSERT INTO `list` VALUES (485, '武术冠军出身，以出演黄飞鸿、方世玉等角色为国人所熟知的武打明星是谁？', '李连杰');
INSERT INTO `list` VALUES (486, '与刘德华，张学友，郭富城合称为香港“四大天王”的人是谁？', '黎明');
INSERT INTO `list` VALUES (487, '歌词“东方之珠，我的爱人”中，东方之珠指的是哪座城市？', '香港');
INSERT INTO `list` VALUES (488, '于 2012 年提出破产保护的原世界最大的照相机，胶卷生产供应商是哪家？', '柯达');
INSERT INTO `list` VALUES (489, '我国的吉利汽车公司成功收购了外国哪家汽车公司 100%的股权？', '沃尔沃');
INSERT INTO `list` VALUES (490, '在“小虎队”成员中，吴奇隆被称为什么虎？', '霹雳虎');
INSERT INTO `list` VALUES (491, '在《三国演义》中， “一个愿打一个愿挨”形容的是周瑜与哪位将领的故事？', '黄盖');
INSERT INTO `list` VALUES (492, '小说《封神演义》中，哪位著名的的人物用直的鱼钩钓鱼？', '姜太公');
INSERT INTO `list` VALUES (493, '在我国可兑换的国际通用外币中，最值钱的是哪个币种？', '英镑');
INSERT INTO `list` VALUES (494, '我国明代“七下西洋”的航海家是谁？', '郑和');
INSERT INTO `list` VALUES (495, '解放战争时期著名的“三大战役”中第一个打响的是哪个战役？', '辽沈战役');
INSERT INTO `list` VALUES (496, '股票交易中经常提到的术语“一手” ，请问“一手”是指多少股？', '100 股');
INSERT INTO `list` VALUES (497, '香港特别行政区的区花是什么？', '紫荆花');
INSERT INTO `list` VALUES (498, '我们通常吃的葵瓜子是什么植物的果实？', '向日葵');
INSERT INTO `list` VALUES (499, '国产动画片《喜羊羊与灰太狼》中，灰太狼的老婆叫什么名字？', '红太狼');
INSERT INTO `list` VALUES (500, ' 琼瑶电视剧《还珠格格》中紫薇格格的亲生母亲叫什么名字？', '夏雨荷');
INSERT INTO `list` VALUES (501, ' 收藏有油画《蒙娜丽莎》等珍贵作品的法国博物馆是哪一座？', '卢浮宫');
INSERT INTO `list` VALUES (502, ' 著名的“自由女神”像坐落在美国的哪座城市？', '纽约');
INSERT INTO `list` VALUES (503, ' 唐朝盛世“贞观之治”出现于哪位皇帝的执政时期？', '唐太宗');
INSERT INTO `list` VALUES (504, ' 历史上“焚书坑儒”的只中国的那一位皇帝？', '秦始皇');
INSERT INTO `list` VALUES (505, ' 2008 北京奥运会开幕式上，领唱《歌唱祖国》的小女孩叫什么？', '林妙可');
INSERT INTO `list` VALUES (506, ' 28 年作为央视春节联欢晚会结尾曲的歌曲叫什么名字？', '难忘今宵');
INSERT INTO `list` VALUES (507, ' “当初是你要分开，分开就分开”这是哪首流行歌曲的歌词？', '爱情买卖');
INSERT INTO `list` VALUES (508, ' 导演张艺谋最新上映的电影是哪一部？', '金陵十三衩');
INSERT INTO `list` VALUES (509, ' 演员房祖名的爸爸是哪位著名功夫巨星？', '成龙');
INSERT INTO `list` VALUES (510, ' 南非世界杯期间，成功预测战况而出名的章鱼叫什么名字？', '保罗');
INSERT INTO `list` VALUES (511, ' 带领中国国家足球队打入 02 年世界杯的外籍主教练是哪一位？', '米卢');
INSERT INTO `list` VALUES (512, ' 世界第一高峰是我国的什么山峰？', '珠穆朗玛峰');
INSERT INTO `list` VALUES (513, ' 迎客松是我国那个著名风景区的标志性景点？', '黄山');
INSERT INTO `list` VALUES (514, ' “狗不理包子”是中国哪个城市的传统风味小吃？', '天津');
INSERT INTO `list` VALUES (515, ' 吃菠萝的时候人们一般会用什么水泡一会儿来减少麻木刺痛感？', '盐水');
INSERT INTO `list` VALUES (516, ' 清朝被称为“扬州八怪”的八个人中以画竹子闻名的是哪一位？', '郑板桥');
INSERT INTO `list` VALUES (517, ' 越剧《十八相送》是描写了哪段古代爱情故事中的情节？', '梁山伯与祝英台');
INSERT INTO `list` VALUES (518, ' 烟草里毒性最大的物质是什么？', '尼古丁');
INSERT INTO `list` VALUES (519, ' 我们通常所说的“干冰”是那种气体的固态存在方式？', '二氧化碳');
INSERT INTO `list` VALUES (520, ' 83 版的《射雕英雄传》中是哪位演员扮演了黄蓉？', '翁美玲');
INSERT INTO `list` VALUES (521, ' 哪位作家在首届《新概念作文大赛》中荣获一等奖，并成为了职业赛车手？', '韩寒');
INSERT INTO `list` VALUES (522, ' 2011 年以“一秒变格格”在网络迅速蹿红的台湾女艺人的俗称是什么？', 'hold 住姐');
INSERT INTO `list` VALUES (523, ' 小说《封神演义》中，传说由狐狸精变成的商纣王宠妃是谁？', '苏妲己');
INSERT INTO `list` VALUES (524, '曹雪芹的《红楼梦》中，葬花的人是谁？', '林黛玉');
INSERT INTO `list` VALUES (525, ' 中国神话当中，嫦娥在月亮上住的行宫叫什么？', '广寒宫');
INSERT INTO `list` VALUES (526, ' 白娘子在端午节是因为喝了什么酒而现出了原形？', '雄黄酒');
INSERT INTO `list` VALUES (527, ' 我国哪个古镇以生产瓷器而闻名于世？', '景德镇');
INSERT INTO `list` VALUES (528, ' 老北京居民居住的院落式组合建筑一般被称作什么？', '四合院');
INSERT INTO `list` VALUES (529, ' 吴承恩小说《西游记》当中，唐僧在哪条河收了沙和尚做徒弟？', '流沙河');
INSERT INTO `list` VALUES (530, ' 金庸小说《倚天屠龙记》中，金毛狮王叫什么名字？', '谢逊');
INSERT INTO `list` VALUES (531, ' 2004 年雅典奥运会中，获奖运动员头带的头环使用哪种植物的枝叶编织成的？', '橄榄');
INSERT INTO `list` VALUES (532, ' 2010 年南非足球世界杯，夺得冠军的是哪个国家的球队？', '西班牙');
INSERT INTO `list` VALUES (533, ' 有“铁榔头”一称的前中国排球女运动员是谁？', '郎平');
INSERT INTO `list` VALUES (534, ' 创办“精武门”的中国清末爱国武术家是谁？', '霍元甲');
INSERT INTO `list` VALUES (535, ' “有一个老人在中国的南海边画了一个圈”是哪首歌的歌词？', '春天的故事');
INSERT INTO `list` VALUES (536, ' 世界三大男高音中的帕瓦罗蒂是哪国人？', '意大利');
INSERT INTO `list` VALUES (537, ' 马可波罗是在哪个朝代来到中国的？', '元朝');
INSERT INTO `list` VALUES (538, ' 传说为关羽“刮骨疗伤”的是哪一位名医？', '华佗');
INSERT INTO `list` VALUES (539, ' 世界上有“钢琴诗人”之称的波澜钢琴家是哪一位？', '肖邦');
INSERT INTO `list` VALUES (540, ' 《马赛曲》是哪一位国家的国歌？', '法国');
INSERT INTO `list` VALUES (541, ' 奥运会上首次只有女性可以参加的比赛项目，是花样游泳和什么项目？', '艺术体操');
INSERT INTO `list` VALUES (542, ' 通常所说的计算机的“大脑”指的是电脑的什么部件？', 'CPU');
INSERT INTO `list` VALUES (543, ' 广东话中的“老豆”是指普通话中的哪种称谓？', '父亲');
INSERT INTO `list` VALUES (544, ' 2010 年世界杯时阿根廷队的教练是谁？', '马拉多纳');
INSERT INTO `list` VALUES (545, ' 姚明曾经在 nba（美国职业男子篮球联盟）为那一只队伍效力？', '火箭');
INSERT INTO `list` VALUES (546, ' 格林童话《灰姑娘》中，灰姑娘参加舞会时所做的车是由哪种植物变成的？', '南瓜');
INSERT INTO `list` VALUES (547, ' 美国历史上著名的演讲《我有一个梦想》的演讲者是谁？', '马丁路德金');
INSERT INTO `list` VALUES (548, ' 电影《泰坦尼克号》的主题曲叫做？', '我心永恒');
INSERT INTO `list` VALUES (549, ' 由百位明星共同演唱的奥运歌曲《北京欢迎你》的曲作者是谁？', '小柯');
INSERT INTO `list` VALUES (550, ' 我们通常所说“煤气中毒”是由于煤气中哪种气体吸入过量造成的？', '一氧化碳');
INSERT INTO `list` VALUES (551, ' 冰箱或空调泄露的哪种物质会破坏大气层臭氧层？', '氟利昂');
INSERT INTO `list` VALUES (552, ' 南非世界杯足球赛决赛阶段共有多少支参赛球队？', '32');
INSERT INTO `list` VALUES (553, ' 现代奥运会起源于哪个国家？', '希腊');
INSERT INTO `list` VALUES (554, ' “遥知兄弟登高处，遍插茱萸少一人” ，描述的是什么节日？', '重阳节');
INSERT INTO `list` VALUES (555, ' 佛教中高僧经过火化后留下的结晶体，被作为圣物供奉的叫什么？', '舍利子');
INSERT INTO `list` VALUES (556, ' 中国 2010 年上海世博会吉祥物叫什么？', '海宝');
INSERT INTO `list` VALUES (557, ' 经常被用来辨别方向的北极星是属于哪个星座的？', '小熊星座');
INSERT INTO `list` VALUES (558, ' 中国历史上唯一一位正式签署文书离婚的皇帝是？', '溥仪');
INSERT INTO `list` VALUES (559, ' 陕西乾陵的“无字碑” ，是哪位皇帝的功德碑？', '武则天');
INSERT INTO `list` VALUES (560, ' 标准中国象棋中，一共有多少个棋子？', '32');
INSERT INTO `list` VALUES (561, '我们通常用来指代飞碟等不明飞行物的英文缩写是什么？', 'UFO');
INSERT INTO `list` VALUES (562, '中国邮政特快专递的英文缩写是哪三个字母？', 'EMS');
INSERT INTO `list` VALUES (563, '著名的“埃菲尔铁塔”是哪个城市的标志性景点？', '巴黎');
INSERT INTO `list` VALUES (564, '考拉，又叫做树袋熊，是哪个国家的国宝动物？', '澳大利亚');
INSERT INTO `list` VALUES (565, '童话故事中，一说谎话鼻子就会变长的木偶叫什么名字？', '匹诺曹');
INSERT INTO `list` VALUES (566, '久负盛名的孔雀舞是我国哪个民族的传统舞蹈？', '傣族');
INSERT INTO `list` VALUES (567, '传统服饰的旗袍是根据哪个民族的服饰改良的？', '满族');
INSERT INTO `list` VALUES (568, '童话故事《皮皮鲁和鲁西西》系列的作者是谁？', '郑渊洁');
INSERT INTO `list` VALUES (569, '制作木乃伊最著名的古代国家是哪一个？', '埃及');
INSERT INTO `list` VALUES (570, '秦始皇兵马俑是在我国的哪个省发掘的？', '陕西');
INSERT INTO `list` VALUES (571, '“宝马”汽车是哪个国家的著名品牌？', '德国');
INSERT INTO `list` VALUES (572, '“迪斯尼”的总部设在哪个国家？', '美国');
INSERT INTO `list` VALUES (573, '被誉为“人间天使”的《罗马假日》女主角是谁？', '奥黛丽赫本');
INSERT INTO `list` VALUES (574, '50年代以被风吹起裙子的标志，红遍世界的美国性感女神是谁？', '玛丽莲梦露');
INSERT INTO `list` VALUES (575, '我国传统观的“七夕”节是为了纪念那两位人物的爱情故事？', '牛郎织女');
INSERT INTO `list` VALUES (576, '我国哪个传统节日是祭祖和扫墓的日子？', '清明节');
INSERT INTO `list` VALUES (577, '人们一般撒什么东西来快速融化积雪路面？', '盐');
INSERT INTO `list` VALUES (578, '酿造啤酒的主要原料是什么粮食？', '麦子');
INSERT INTO `list` VALUES (579, '我们经常用的“飘柔”洗发水，是美国哪家公司的产品？', '宝洁');
INSERT INTO `list` VALUES (580, '发源于澳洲，近几年大火的雪地靴，统称是哪三个英文字母？', 'ugg');
INSERT INTO `list` VALUES (581, '2004年夏季奥运会是在那个城市举办的？', '雅典');
INSERT INTO `list` VALUES (582, '前英格兰足球队队长，并成为伦敦奥运会形象大使的球星是谁？', '贝克汉姆');
INSERT INTO `list` VALUES (583, '以“莫须有”罪名毒害了名将岳飞的奸臣是谁？', '秦桧');
INSERT INTO `list` VALUES (584, '著名的“特洛伊之战”传说起因是双方为了争夺一个美女，请问这位美女叫什么？', '海伦');
INSERT INTO `list` VALUES (585, '有史以来第一个活着亲眼看到自己的作品被收藏进卢浮宫的西班牙画家是谁？', '毕加索');
INSERT INTO `list` VALUES (586, '传说中开天辟地的上古人物叫做什么？', '盘古');
INSERT INTO `list` VALUES (587, '中国神话传说中是哪位神用五色石头补的天？', '女娲');
INSERT INTO `list` VALUES (588, '因为四季如春而被称为“春城”的是我国哪个城市？', '昆明');
INSERT INTO `list` VALUES (589, '坐落在上海黄浦江畔的著名电视塔，叫做什么名字？', '东方明珠');
INSERT INTO `list` VALUES (590, '公认为全世界规模最大的网络搜索引擎是哪一个？', '谷歌');
INSERT INTO `list` VALUES (591, '05年联想公司正式宣布完成收购哪一家公司的全球个人电脑业务？', 'IBM');
INSERT INTO `list` VALUES (592, '被誉为香港第一代“玉女掌门人”，与倪震结婚的女明星是谁？', '周慧敏');
INSERT INTO `list` VALUES (593, '1987年徐克导演拍的《倩女幽魂》中饰演宁采臣的男主角是谁？', '张国荣');
INSERT INTO `list` VALUES (594, '我国一般查询电话号码通用的三位数号码是多少？', '114');
INSERT INTO `list` VALUES (595, '我国首都北京市的电话区号，是哪三个数字？', '010');
INSERT INTO `list` VALUES (596, '凭借《花样年华》在第53届戛纳电影节荣获最佳男主角的人是谁？', '梁朝伟');
INSERT INTO `list` VALUES (597, '指导《断背山》《卧虎藏龙》等电影的著名导演叫什么？', '李安');
INSERT INTO `list` VALUES (598, '皮肤划破后渗出的血会自动凝结是因为血液中含有什么细胞？', '血小板');
INSERT INTO `list` VALUES (599, '人体受到细菌感染时，血液中的那种细胞会明显增多？', '白血球');
INSERT INTO `list` VALUES (600, '世界上通常用来导航的全球卫星定位系统的英文简称是什么？', 'GPS');
INSERT INTO `list` VALUES (601, '经常听说的“工商管理硕士”的英文简称是什么？', 'MBA');
INSERT INTO `list` VALUES (602, '电影《盗梦空间》中，莱昂纳多饰演的主角用来分辨真实与梦境的道具是什么？', '陀螺');
INSERT INTO `list` VALUES (603, '电影《2012》中，用来拯救人类的方舟，建在哪个地区？', '西藏');
INSERT INTO `list` VALUES (604, '理性纯洁的精神恋爱又被人们称为哪位哲学家式的爱情？', '柏拉图');
INSERT INTO `list` VALUES (605, '卡通人物米老鼠和唐老鸭是哪位艺术家创造的经典形象？', '迪斯尼');
INSERT INTO `list` VALUES (606, '和《大学》，《孟子》，《中庸》一起被称为中国“四书”的是哪本著作？', '《论语》');
INSERT INTO `list` VALUES (607, '北京奥运会徽是一枚中国印，请问印章上的人形是由什么汉字演化而成？', '京');
INSERT INTO `list` VALUES (608, '希腊神话当中，顾影自怜的美男子那喀索斯变成了什么植物？', '水仙花');
INSERT INTO `list` VALUES (609, '一般被称为“万能献血者”的血型是什么？', 'o型');
INSERT INTO `list` VALUES (610, '我们常说的“一打”啤酒是指多少瓶啤酒？', '12瓶');

SET FOREIGN_KEY_CHECKS = 1;
